//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_QLS_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DauSach()
        {
            this.CT_HOADON = new HashSet<CT_HOADON>();
        }
    
        public int Masach { get; set; }
        public string TuaSach { get; set; }
        public string TacGia { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<System.DateTime> NgayXuatBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        public virtual LoaiSach LoaiSach { get; set; }
    }
}
